# Generated by Django 4.0.5 on 2022-06-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_work_start', models.DateField(verbose_name='Дата начала смены')),
                ('date_work_finish', models.DateField(verbose_name='Дата окончания смены')),
                ('time_start', models.TimeField(verbose_name='Начало смены')),
                ('time_finish', models.TimeField(verbose_name='Конец смены')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Специальность')),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.location', verbose_name='Место работы')),
                ('schedule', models.ManyToManyField(blank=True, related_name='schedule', to='workersbooking.schedules', verbose_name='Расписание')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.specialities', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_name', models.CharField(max_length=255, verbose_name='Процедура')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя посетителя')),
                ('starting_date', models.DateField(verbose_name='Дата начала процедуры')),
                ('finish_date', models.DateField(verbose_name='Дата окончания процедуры')),
                ('starting_time', models.TimeField(verbose_name='Время начала процедуры')),
                ('finish_time', models.TimeField(verbose_name='Время конца процедуры')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.workers', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
