# Generated by Django 4.0.5 on 2022-06-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_name', models.CharField(max_length=255, verbose_name='Процедура')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя посетителя')),
                ('starting_datetime', models.DateTimeField(verbose_name='Начало процедуры')),
                ('finish_datetime', models.DateTimeField(verbose_name='Конец процедуры')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Начало смены')),
                ('date_finish', models.DateTimeField(verbose_name='Конец смены')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('booked_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.booking', verbose_name='Записи')),
                ('working_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.location', verbose_name='Место работы')),
                ('working_schedule', models.ManyToManyField(blank=True, null=True, to='workersbooking.schedules', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AddField(
            model_name='schedules',
            name='worker',
            field=models.ManyToManyField(null=True, to='workersbooking.workers', verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workersbooking.workers', verbose_name='Мастер'),
        ),
    ]
