# Generated by Django 4.0.5 on 2022-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='booked_proc',
        ),
        migrations.AddField(
            model_name='workers',
            name='booked_proc',
            field=models.ManyToManyField(blank=True, to='workersbooking.booking', verbose_name='Записи'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='working_schedule',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='workersbooking.schedules', verbose_name='Расписание'),
        ),
    ]
